project:
  type: website
  output-dir: docs
  

website:
  title: "Cristinas Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Assignment 2
        href: Lab01.qmd
      - text: Assignment 2.5
        href: Lab02.qmd
      - href: Lab03.qmd
        text: Assignment 3
      - href: Assignment4.qmd
        text: Assignment 4
      - href: Lab04_UL.qmd
        text: Assignment 5
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    


editor: visual

